"""Per-trigger-kind playbooks: strategy, send_as, CTA, mandatory facts, forbidden phrasing."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class Playbook:
    send_as_merchant: str
    send_as_no_customer: str
    cta_default: str
    template_name: str
    message_objective: str
    emotional_frame: str
    cta_style: str
    voice_emphasis: str
    mandatory_fact_keys: List[str] = field(
        default_factory=list
    )  # logical keys from facts.derived / trigger
    must_include: List[str] = field(default_factory=list)
    forbidden: List[str] = field(default_factory=list)


KIND_ALIASES = {
    "search_spike": "perf_spike",
    "competitor_offer_seen": "competitor_opened",
    "dormant_customer_pool": "customer_lapsed_soft",
    "low_rating_visibility": "review_theme_emerged",
    "abandoned_campaign": "dormant_with_vera",
    "festive_window": "festival_upcoming",
    "lunch_dinner_gap": "curious_ask_due",
    "lead_unanswered": "dormant_with_vera",
}


def get_playbook(kind: str) -> Playbook:
    k = KIND_ALIASES.get((kind or "").lower(), (kind or "").lower())
    if k in PLAYBOOKS:
        return PLAYBOOKS[k]
    return PLAYBOOKS["default"]


def resolve_send_as(pb: Playbook, customer: Optional[dict], trigger_scope: str) -> str:
    if customer and trigger_scope == "customer":
        return pb.send_as_merchant
    return pb.send_as_no_customer


PLAYBOOKS: dict[str, Playbook] = {
    "research_digest": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_research_digest_v1",
        message_objective="Turn fresh clinical insight into a patient-ed asset this merchant can send.",
        emotional_frame="Peer credibility + ‘this fits your roster’ — not hype.",
        cta_style="Single open question: draft abstract + WhatsApp?",
        voice_emphasis="Cite digest source; tie to high-risk cohort / CTR gap if in facts.",
        mandatory_fact_keys=[
            "digest_item.title",
            "digest_item.source",
            "derived.customer_aggregate_snapshot.high_risk_adult_count",
        ],
        must_include=["trial_n or summary number from digest", "source line"],
        forbidden=["guaranteed cure", "miracle"],
    ),
    "regulation_change": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_compliance_v1",
        message_objective="Drive a dated compliance action before the rule lands.",
        emotional_frame="Calm urgency — bounded risk, clear deadline.",
        cta_style="YES = audit checklist",
        voice_emphasis="Deadline from payload/digest only.",
        mandatory_fact_keys=["trigger.payload.deadline_iso", "digest_item.title"],
        must_include=["deadline", "rule headline"],
        forbidden=["panic", "shut down"],
    ),
    "recall_due": Playbook(
        send_as_merchant="merchant_on_behalf",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="merchant_recall_reminder_v1",
        message_objective="Fill a recall slot with the merchant’s real offer price.",
        emotional_frame="Helpful + specific time — not guilt.",
        cta_style="YES / suggest another time",
        voice_emphasis="Customer first name; slots from trigger; active offer title.",
        mandatory_fact_keys=[
            "customer.identity.name",
            "trigger.payload.available_slots",
            "derived.best_live_offer_title",
        ],
        must_include=["slots", "₹ price if in offer title"],
        forbidden=["you must visit", "mandatory treatment"],
    ),
    "perf_dip": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_perf_dip_v1",
        message_objective="Recover conversion when a metric slips — tie to listing + live offer.",
        emotional_frame="Operator-to-operator: ‘visibility vs calls’ tension if present.",
        cta_style="YES = draft post + SMS",
        voice_emphasis="Metric + delta_pct from trigger; peer CTR; best_live_offer.",
        mandatory_fact_keys=[
            "trigger.payload.metric",
            "trigger.payload.delta_pct",
            "derived.performance_tension",
            "derived.best_live_offer_title",
        ],
        must_include=["metric", "delta %", "one live offer or locality"],
        forbidden=["everything is fine", "generic discount"],
    ),
    "renewal_due": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_renewal_v1",
        message_objective="Close renewal before subscription laps.",
        emotional_frame="Factual countdown — respect their time.",
        cta_style="YES = send renewal link copy",
        voice_emphasis="days_remaining, plan, renewal_amount from trigger.",
        mandatory_fact_keys=["trigger.payload.days_remaining", "trigger.payload.plan"],
        must_include=["days left", "plan name"],
        forbidden=["you will lose everything"],
    ),
    "festival_upcoming": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_festival_v1",
        message_objective="Lock a seasonal bundle using merchant’s active offers.",
        emotional_frame="Seasonal relevance without hard sell.",
        cta_style="Open: bundle draft?",
        voice_emphasis="Festival name + days_until; best_live_offer_title.",
        mandatory_fact_keys=["trigger.payload.festival", "derived.best_live_offer_title"],
        must_include=["festival", "days or date"],
        forbidden=["limited time only!!!"],
    ),
    "wedding_package_followup": Playbook(
        send_as_merchant="merchant_on_behalf",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="merchant_bridal_followup_v1",
        message_objective="Convert bridal prep window into a booked package.",
        emotional_frame="Excitement + countdown — grounded in trial date.",
        cta_style="YES = hold slot",
        voice_emphasis="days_to_wedding; active bridal-related offer if present.",
        mandatory_fact_keys=[
            "customer.identity.name",
            "trigger.payload.days_to_wedding",
            "derived.best_live_offer_title",
        ],
        must_include=["wedding timing", "one price-forward offer"],
        forbidden=["guaranteed perfect skin"],
    ),
    "curious_ask_due": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_curious_ask_v1",
        message_objective="Pull one ‘most asked service’ signal for content.",
        emotional_frame="Low stakes curiosity — you’ll do the work.",
        cta_style="Reply with service name",
        voice_emphasis="Locality + business name; optional top_trend_query as hint.",
        mandatory_fact_keys=["merchant.identity.locality", "derived.top_trend_query_near_me"],
        must_include=["one local or trend anchor"],
        forbidden=["increase sales"],
    ),
    "winback_eligible": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_winback_merchant_v1",
        message_objective="Win back subscription with concrete days-since-expiry.",
        emotional_frame="Second chance — numbers only.",
        cta_style="YES = 3-line WhatsApp",
        voice_emphasis="days_since_expiry; lapsed customers if in payload.",
        mandatory_fact_keys=["trigger.payload.days_since_expiry"],
        must_include=["expiry gap days"],
        forbidden=["you are losing ranking forever"],
    ),
    "ipl_match_today": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_ipl_match_v1",
        message_objective="Route demand to the right daypart/offer for match day.",
        emotional_frame="Operator savvy — delivery vs dine-in nuance.",
        cta_style="YES = creatives in 10 min",
        voice_emphasis="Match + venue from trigger; is_weeknight; BOGO/active offer.",
        mandatory_fact_keys=["trigger.payload.match", "derived.best_live_offer_title"],
        must_include=["match detail", "existing offer"],
        forbidden=["guaranteed packed house"],
    ),
    "review_theme_emerged": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_review_theme_v1",
        message_objective="Fix a recurring review theme with a checklist + reply.",
        emotional_frame="Constructive — quote frequency shows it’s real.",
        cta_style="YES = fix-it draft",
        voice_emphasis="theme, occurrences_30d, common_quote.",
        mandatory_fact_keys=[
            "trigger.payload.theme",
            "trigger.payload.occurrences_30d",
        ],
        must_include=["theme count", "snippet"],
        forbidden=["ignore reviews"],
    ),
    "milestone_reached": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_milestone_v1",
        message_objective="Push past an imminent milestone with social proof content.",
        emotional_frame="Momentum — almost there.",
        cta_style="Open: thank-you post?",
        voice_emphasis="value_now vs milestone_value.",
        mandatory_fact_keys=[
            "trigger.payload.value_now",
            "trigger.payload.milestone_value",
        ],
        must_include=["current vs target numbers"],
        forbidden=["buy reviews"],
    ),
    "active_planning_intent": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_confirm_cancel",
        template_name="vera_planning_intent_v1",
        message_objective="Answer ‘what would it look like’ with a concrete draft outline.",
        emotional_frame="You asked — here’s the artifact.",
        cta_style="CONFIRM to paste full copy",
        voice_emphasis="merchant_last_message echo; intent_topic; best offer as price anchor.",
        mandatory_fact_keys=[
            "trigger.payload.intent_topic",
            "trigger.payload.merchant_last_message",
            "derived.best_live_offer_title",
        ],
        must_include=["their last line", "one numeric price if available"],
        forbidden=["another qualifying question"],
    ),
    "seasonal_perf_dip": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_seasonal_dip_v1",
        message_objective="Normalize seasonal dip; pivot to retention.",
        emotional_frame="Anxiety relief + disciplined spend.",
        cta_style="YES = retention challenge draft",
        voice_emphasis="delta_pct + member count; season_note.",
        mandatory_fact_keys=[
            "trigger.payload.delta_pct",
            "derived.customer_aggregate_snapshot.total_active_members",
        ],
        must_include=["dip %", "member count if present"],
        forbidden=["your business is failing"],
    ),
    "customer_lapsed_hard": Playbook(
        send_as_merchant="merchant_on_behalf",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="merchant_winback_customer_v1",
        message_objective="Win back a cold member with no-shame + real trial offer.",
        emotional_frame="Welcome back — no guilt trip.",
        cta_style="YES = hold trial",
        voice_emphasis="days_since_last_visit; previous_focus; first active offer.",
        mandatory_fact_keys=[
            "trigger.payload.days_since_last_visit",
            "derived.best_live_offer_title",
        ],
        must_include=["days since visit", "offer name"],
        forbidden=["you have abandoned your health"],
    ),
    "customer_lapsed_soft": Playbook(
        send_as_merchant="merchant_on_behalf",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="merchant_lapsed_soft_v1",
        message_objective="Nudge before hard lapse using visit gap + preference anchor.",
        emotional_frame="Light touch — we saved your usual slot language if in prefs.",
        cta_style="YES = book",
        voice_emphasis="customer preference_anchor; category-appropriate wording.",
        mandatory_fact_keys=["customer.customer_derived.days_since_last_visit"],
        must_include=["visit gap or last_visit date", "offer or service anchor"],
        forbidden=["you never visit"],
    ),
    "trial_followup": Playbook(
        send_as_merchant="merchant_on_behalf",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="merchant_trial_followup_v1",
        message_objective="Book the next session from trial options.",
        emotional_frame="Easy next step.",
        cta_style="YES = block slot",
        voice_emphasis="next_session_options label.",
        mandatory_fact_keys=["trigger.payload.next_session_options"],
        must_include=["next slot label"],
        forbidden=[],
    ),
    "appointment_tomorrow": Playbook(
        send_as_merchant="merchant_on_behalf",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="merchant_appt_tomorrow_v1",
        message_objective="Confirm or reschedule tomorrow’s appointment.",
        emotional_frame="Short utility reminder.",
        cta_style="CONFIRM / RESCHEDULE",
        voice_emphasis="Business name + customer name.",
        mandatory_fact_keys=["customer.identity.name", "merchant.identity.name"],
        must_include=["tomorrow", "business name"],
        forbidden=[],
    ),
    "supply_alert": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_supply_alert_v1",
        message_objective="Operational recall — batches + affected chronic roster.",
        emotional_frame="Urgent but bounded risk wording from payload.",
        cta_style="YES = WA templates + pickup flow",
        voice_emphasis="molecule, batches, chronic_rx_count.",
        mandatory_fact_keys=[
            "trigger.payload.molecule",
            "trigger.payload.affected_batches",
            "derived.customer_aggregate_snapshot.chronic_rx_count",
        ],
        must_include=["batch ids", "molecule"],
        forbidden=["deadly", "panic"],
    ),
    "chronic_refill_due": Playbook(
        send_as_merchant="merchant_on_behalf",
        send_as_no_customer="vera",
        cta_default="binary_confirm_cancel",
        template_name="merchant_refill_v1",
        message_objective="Refill before stock-out date with molecule precision.",
        emotional_frame="Respectful pharmacy tone.",
        cta_style="CONFIRM dispatch",
        voice_emphasis="molecule_list + stock_runs_out_iso.",
        mandatory_fact_keys=["trigger.payload.molecule_list", "trigger.payload.stock_runs_out_iso"],
        must_include=["molecules", "date"],
        forbidden=["guaranteed cure"],
    ),
    "category_seasonal": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_category_seasonal_v1",
        message_objective="Reorder + broadcast for shelf shift trends.",
        emotional_frame="Inventory ops — numbers from payload trends.",
        cta_style="Open: checklist + WA?",
        voice_emphasis="trends list; chronic_rx_count if pharmacy.",
        mandatory_fact_keys=["trigger.payload.trends"],
        must_include=["at least one trend token"],
        forbidden=["everyone is buying"],
    ),
    "gbp_unverified": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_gbp_verify_v1",
        message_objective="Get verification done — cite path + uplift if in payload.",
        emotional_frame="Unlock visibility — factual.",
        cta_style="YES = step list",
        voice_emphasis="verification_path; estimated_uplift_pct.",
        mandatory_fact_keys=["trigger.payload.verification_path"],
        must_include=["verification path"],
        forbidden=["Google owes you"],
    ),
    "cde_opportunity": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_cde_v1",
        message_objective="Fill seats/credits for CDE — calendar + staff reminder.",
        emotional_frame="Professional development — time boxed.",
        cta_style="Reply YES for invite text",
        voice_emphasis="digest title; credits; fee from facts.",
        mandatory_fact_keys=["trigger.payload.digest_item_id", "trigger.payload.credits"],
        must_include=["title", "credits"],
        forbidden=["mandatory attendance"],
    ),
    "competitor_opened": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_competitor_v1",
        message_objective="Counter-position against a nearby competitor offer using YOUR live price.",
        emotional_frame="Voyeur + protect share — no trash talk.",
        cta_style="Open: counter GBP line?",
        voice_emphasis="distance_km, competitor_name, their_offer, your best_live_offer.",
        mandatory_fact_keys=[
            "trigger.payload.competitor_name",
            "trigger.payload.distance_km",
            "derived.best_live_offer_title",
        ],
        must_include=["km or locality", "your active offer"],
        forbidden=["they are terrible"],
    ),
    "perf_spike": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_perf_spike_v1",
        message_objective="Exploit demand spike with a limited post + offer hook.",
        emotional_frame="Momentum — capitalize now.",
        cta_style="Open: limited-time post?",
        voice_emphasis="metric + delta_pct + likely_driver if present.",
        mandatory_fact_keys=["trigger.payload.metric", "trigger.payload.delta_pct"],
        must_include=["spike %", "metric name"],
        forbidden=["double your revenue tonight"],
    ),
    "dormant_with_vera": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_dormant_v1",
        message_objective="Re-open thread after silence — one high-leverage win.",
        emotional_frame="Light — no guilt.",
        cta_style="YES = 3 post drafts",
        voice_emphasis="days_since_last_merchant_message; unanswered vera flag.",
        mandatory_fact_keys=["trigger.payload.days_since_last_merchant_message"],
        must_include=["silence days"],
        forbidden=["you ignore me"],
    ),
    "cross_domain_safe": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="binary_yes_no",
        template_name="vera_cross_domain_safe_v1",
        message_objective="When trigger semantics do not match merchant vertical, send a generic actionable nudge.",
        emotional_frame="Calm operator-to-operator — no wrong-domain jargon.",
        cta_style="YES = draft notice or checklist",
        voice_emphasis="Owner name + locality only; optional deadline if present.",
        mandatory_fact_keys=["merchant.identity.locality"],
        must_include=["WhatsApp", "Google or listing"],
        forbidden=["DCI", "radiograph", "atorvastatin", "yoga camp", "IPL team names"],
    ),
    "default": Playbook(
        send_as_merchant="vera",
        send_as_no_customer="vera",
        cta_default="open_ended",
        template_name="vera_generic_v1",
        message_objective="Turn the trigger into one concrete merchant action.",
        emotional_frame="Specific over clever.",
        cta_style="One binary or single open question",
        voice_emphasis="Use derived.performance_tension + best_live_offer + locality.",
        mandatory_fact_keys=["trigger.kind", "merchant.identity.locality"],
        must_include=["one number from facts", "trigger kind"],
        forbidden=["increase sales", "boost engagement", "run a campaign today"],
    ),
}
